Ft/payment paystack option/151208546
andela/elrond-rc pull request #15
Opened 2017-10-08 20:26 UTC by THEozmic

#### What does this PR do?
Add wallet checkout and dashboard feature
#### Description of Task to be completed?
A user should be able to checkout using wallet, transfer funds to other users' wallets and fund their wallet
#### How should this be manually tested?
Login, click on "wallet" from the dropdown, provide amount and click on "submit" to fund wallet.
Provide email and amount, click on "transfer" to transfer.
To pay with wallet, click on wallet payment option, click on "pay now"
#### What are the relevant pivotal tracker stories?
#151208546
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/15184445/31320607-3c47ec8a-ac6f-11e7-8aea-233e3fae81d8.png)
![image](https://user-images.githubusercontent.com/15184445/31320611-4983a916-ac6f-11e7-9273-8d89a36480cb.png)

2017-10-11 07:19 UTC, mradeybee requested changes
Had few comments and please look at what is making hound complain about ES6 stuffs.

2017-10-11 07:19 UTC, mradeybee commented on imports/plugins/core/layout/client/templates/layout/wallets/wallet.html
> +</template>
Add an empty line at the end of the file.

2017-10-11 07:19 UTC, mradeybee commented on imports/plugins/core/layout/client/templates/layout/wallets/wallet.js
> +  if (list[0] !== undefined) {
you might want to have `undefined` as a string. I am not totally sure, but I think its safer.

2017-10-11 07:19 UTC, mradeybee commented on imports/plugins/core/layout/client/templates/layout/wallets/wallet.js
> +  document.getElementById("first").disabled = currentPage === 1 ? true : false;
You dont need to write this like this. `currentPage === 1` already returns true or false, so, just do ` document.getElementById("first").disabled = currentPage === 1` and you will be good. Apply this to all other places.

2017-10-11 07:19 UTC, mradeybee commented on imports/plugins/core/layout/client/templates/layout/wallets/wallet.js
> +    public: "pk_test_3e07adc39d17fdb204c221ed2b2319ed6267d4df",
Put keys on env variables.

2017-10-12 12:24 UTC, mradeybee requested changes
This PR looks very identical to https://github.com/andela/elrond-rc/pull/19 what is going on?

2017-10-12 12:24 UTC, mradeybee commented on imports/plugins/core/layout/client/templates/layout/wallets/wallet.js
> +          console.log(paystackResponse.amount, "bleh bleh");
Remove log

2017-10-13 10:43 UTC, THEozmic commented
I accidentally checkout out from this branch

2017-10-13 11:04 UTC, THEozmic commented on imports/plugins/core/layout/client/templates/layout/wallets/wallet.js
> +          console.log(paystackResponse.amount, "bleh bleh");
Done

2017-10-13 15:59 UTC, mradeybee approved these changes

2017-10-13 16:00 UTC, merged